import React from 'react';

const Disclaimer = () => {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white dark:bg-gray-800 rounded-2xl shadow-sm p-8 md:p-12 border border-gray-100 dark:border-gray-700">
        <h1 className="text-3xl font-black font-serif text-gray-900 dark:text-white mb-8">Disclaimer</h1>
        
        <div className="prose dark:prose-invert max-w-none text-gray-600 dark:text-gray-300">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Content Aggregation</h2>
          <p className="mb-4">
            Gathered is an automated news aggregation service. The articles, headlines, and images displayed on this website are automatically sourced from third-party RSS feeds.
            Gathered does not claim ownership of any content displayed. All rights, including copyright, belong to the original publishers.
          </p>

          <h2 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Accuracy of Information</h2>
          <p className="mb-4">
            While we strive to source from reputable publishers, Gathered makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, or availability of the information contained on the website. 
            Any reliance you place on such information is therefore strictly at your own risk.
          </p>

          <h2 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">AI-Generated Content</h2>
          <p className="mb-4">
            Some summaries and categorizations on this platform may be generated by Artificial Intelligence. 
            AI models can occasionally produce errors or hallucinations. Always verify important information with the original source linked in the article card.
          </p>

          <h2 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">External Links</h2>
          <p className="mb-4">
            Through this website, you are able to link to other websites which are not under the control of Gathered. 
            We have no control over the nature, content, and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;